name: ci

on:
  push:
    paths:
      - "**.py"
      - .github/workflows/ci.yml

jobs:

  linux:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - run: pip install .[tests,lint]

    - run: flake8
    - run: mypy

    - run: pytest
